[font]

# Normal font style
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }  # Default for Linux/BSD: "monospace", Regular

# Bold font style
# bold = { style = "Regular" }  # Inherits family from normal, Default style: Bold

# Italic font style
# italic = { style = "Regular" }  # Inherits family from normal, Default style: Italic

# Bold Italic font style
# bold_italic = { style = "Regular" }  # Inherits family from normal, Default style: Bold Italic

# Font size in points
size = 16

[colors]

# Default colors
[colors.primary]
background = '#000000'
foreground = '#dddddd'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#cc0403'
green   = '#19cb00'
yellow  = '#cecb00'
blue    = '#0d73cc'
magenta = '#cb1ed1'
cyan    = '#0dcdcd'
white   = '#dddddd'

# Bright colors
[colors.bright]
black   = '#767676'
red     = '#f2201f'
green   = '#23fd00'
yellow  = '#fffd00'
blue    = '#1a8fff'
magenta = '#fd28ff'
cyan    = '#14ffff'
white   = '#ffffff'

[window]
startup_mode = 'Fullscreen'
